# Introduction: basic Julia usage and plotting

This lecture is an updated and improved version of the highly-viewed ["Julia Zero2Hero" workshop](https://www.youtube.com/watch?v=Fi7Pf2NveH0). The new version includes a dedicated block about plotting, provides simpler explanations, is updated to the newest Julia versions, and has more accessible exercises!

This lecture is also used as the first lecture in a full course series called [**Nonlinear Dynamics and Complex Systems analysis with Julia**](https://github.com/JuliaDynamics/NonlinearDynamicsComplexSystemsCourse)!

## Why should I learn Julia?


[Julia](https://julialang.org/) is a relatively new programming language, developed at MIT, with version 1.0 released in August 2018. Even though it is so recent, it has taken the scientific community by storm and many serious large scale projects have started using Julia.

The [Julia documentation](https://docs.julialang.org/en/v1/) outlines the main facts and features of Julia. I have summarized my opinions on why Julia is the best choice for scientific computing in this [GitHub page](https://github.com/Datseris/whyjulia-manifesto).

# Basics of Julia

In this block we will overview basic Julia syntax, data structures, iteration, and using functions. The block assumes familiarity with programming, in the sense of reasoning about code, and also familiarity with the concept of an interactive development environment (or dynamic programming languages) where a program may be written and executed interactively line-by-line. The block doesn't assume any familiarity with a specific programming language however.

## Basic syntax


### Assignment

Assignment of variables in Julia is done with the `=` sign.

In [1]:
x = 1

1

In [2]:
x

1

You can assign *anything* to a variable binding. This includes functions, modules, data types, or whatever you can come up with.

Variable names can include practically any Unicode character. Additionally, most Julia editing environments offer "LaTeX Completion". Pressing e.g. `\delta` and then TAB will create the corresponding Unicode character using the LaTeX syntax.

In [3]:
δ = 4 # type `\delta` and then press tab!

4

You can assign multiple variables to multiple values using commas.

In [4]:
😺, 😀, 😞 = 1, 0, -1

(1, 0, -1)

In [5]:
😺 + 😞 == 😀 # legitimate code. Not good for readability though ;)

true

Strings are created between double quotes `"` while the single quotes `'` are used for characters only.

In [6]:
안녕하세요 = "人人生而自由，在尊严和权利上一律平等。"

"人人生而自由，在尊严和权利上一律平等。"

In [7]:
char = '안' # for characters, Julia prints their Unicode information

'안': Unicode U+C548 (category Lo: Letter, other)

Since assignment returns the value, by default this value is printed. This is **AMAZING**, but you can also silence printing by adding `;` to the end of the expression:

In [8]:
x = 3;

Lastly, you can interpolate any expression into a string using `$(expression)`

In [9]:
"the value of the cat face (😺) is $(😺)"

"the value of the cat face (😺) is 1"

In [10]:
"I am doing math inside a string: $(π^2 - x)"

"I am doing math inside a string: 6.869604401089358"

### Math operations

Basic math operators are `+, -, *, /` and `^` for power.

In [11]:
x = 3
y = x^2.6

17.398638404385867

Most julia operators have their `=` version, which updates something with its own value

In [12]:
x += 3 # x = x + 3
x -= 3
x *= 2
x /= 2

3.0

Literal numbers can multiply anything without having to put `*` inbetween, as long as the number is on the left side:

In [13]:
5x - 12.54y * 1.2e-5x

14.992145558678724

## Type basics

Everything that exists in Julia has a certain **Type**. (e.g. numbers can be integers, floats, rationals). This "type system" is instrumental for the inner workings of Julia, and is mainly what enables Julia to have performance matching static languages like C.

The type system also enables **Multiple Dispatch**, one of Julia's greatest features, which we will cover in the second lecture.

To find the type of a thing in Julia you simply use `typeof(thing)`:

In [14]:
x = 3
typeof(x)

Int64

In [15]:
typeof(1.5)

Float64

In [16]:
typeof(1.5f0)

Float32

In [17]:
typeof("asdf")

String

## Basic collection datastructures

Indexing a collection (like an array or a dictionary) in Julia is done with brackets: `collection[index]`.

In **ordered collections** (where the elements are specified by their order rather than some key), indexing is done using the positive integers. This means that **indexing in Julia starts from 1, which is exceptionally good,** because the index matches the element order: the 5th element has index 5.


### Tuples
Tuples are **immutable ordered collections** of elements of any type. They are most useful when the elements are not of the same type with each other and are intended only for small collections.

Syntax:

```julia
(item1, item2, ...)
```

In [18]:
myfavoritethings = ("purple", '🥁', π)

("purple", '🥁', π)

In [19]:
myfavoritethings[1]

"purple"

You can extract multiple values into variables from any collection using commas.

In [20]:
a, b, c = myfavoritethings
c

π = 3.1415926535897...

The type of the tuple is the type of its constituents.

In [21]:
typeof(myfavoritethings)

Tuple{String, Char, Irrational{:π}}

### Dictionaries
Dictionaries are **unordered mutable collections** of pairs key-value. They are intended for sets of relational data, and typically you want the data to be of the same type.

Syntax:
```julia
Dict(key1 => value1, key2 => value2, ...)
```

A good example of a dictionary is a contacts list, where we associate names with phone numbers.

In [22]:
myphonebook = Dict("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String, String} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [23]:
myphonebook["Jenny"]

"867-5309"

New entries can be added to the above dictionary, because it is mutable *(I will talk in more detail about mutability in a moment, but for now mutable means that "you can change its values without creating a copy or a new collection")*. The key of the entry must be of type `String` and the value of the entry must be of type `String`, because these are the types in the original dictionary.

In [24]:
myphonebook["Buzz Lightyear"] = "∞ and beyond"

myphonebook # this displays the phonebook

Dict{String, String} with 3 entries:
  "Jenny"          => "867-5309"
  "Buzz Lightyear" => "∞ and beyond"
  "Ghostbusters"   => "555-2368"

Dictionaries have a specific type for keys and values. First type is the type of key, second is the type of value.

In [25]:
typeof(myphonebook)

Dict{String, String}

### Named tuples

_(optional subsection that is typically skipped)_

These are exactly like tuples but also assign a name to each variable they contain.
Hence, they are an **immutable collection of ordered _and_ named elements**. 
They rest between the `Tuple` and `Dict` type in their use.

Their syntax is:
```julia
(key1 = val1, key2 = val2, ...)
```
For example:

In [26]:
nt = (x = 5, y = "str", z = 5/3)

(x = 5, y = "str", z = 1.6666666666666667)

These objects can be accessed with `[1]` like normal tuples, but also with the syntax `.key`:

In [27]:
nt[1]

5

In [28]:
nt.x # equivalent with nt[:x]

5

(named tuples are useful to know, because keyword arguments to functions are essentially named tuples)

### Arrays

The standard Julia `Array` is a **mutable and ordered collection of items of the same type**.
The dimensionality of the Julia array is important. A `Matrix` is an array of dimension 2. A `Vector` is an array of dimension 1. The *element type* of what an array contains is irrelevant to its dimension!

**i.e. a Vector of Vectors of Numbers and a Matrix of Numbers are two totally different things!**

The syntax to make a vector is enclosing elements in brackets:

In [29]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [30]:
mixture = [1, 1, 2, 3, "Ted", "Robyn"]

6-element Vector{Any}:
 1
 1
 2
 3
  "Ted"
  "Robyn"

As mentioned, the type of the elements of an array must be the same. Yet above we mix numbers with strings! I wasn't lying though; the above vector is an **unoptimized** version that can hold **any** thing. You can see this in the type of the vector, `Vector{Any}`.

Arrays of other data structures, e.g. vectors or dictionaries, or anything, as well as multi-dimensional arrays are possible:

In [31]:
vec_vec_num = [[1, 2, 3], [4, 5], [6, 7, 8, 9]] # vector of vectors, which is NOT a matrix

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

If you want to make a matrix, two ways are the most common: (1) specify each entry one by one

In [32]:
matrix = [1 2 3; # elements in same row separated by space
          4 5 6; # semicolon means "go to next row"
          7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

or (2), you use a function that initializes a matrix. E.g. `rand(n, m)` will create an `n×m` matrix with uniformly random numbers

In [33]:
R = rand(4, 3)

4×3 Matrix{Float64}:
 0.046139   0.50836   0.908017
 0.0355579  0.401262  0.415857
 0.376893   0.278715  0.882313
 0.779987   0.96423   0.838438

In [34]:
R[1, 2] # two dimensional indexing

0.5083598581385742

Since arrays are mutable we can change their entries _in-place_ (i.e., without creating a new array):

In [35]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]
fibonacci[1] = 15
fibonacci

7-element Vector{Int64}:
 15
  1
  2
  3
  5
  8
 13

We can add or remove elements from any mutable collection with functions like `push!, pop!, delete!`. We'll cover functions in more detail in a moment!

In [36]:
push!(fibonacci, 21)

8-element Vector{Int64}:
 15
  1
  2
  3
  5
  8
 13
 21

Lastly, for multidimensional arrays, the `:` symbol is useful, which means to "select all elements in this dimension".

In [37]:
x = rand(3, 3)

3×3 Matrix{Float64}:
 0.609454  0.367463  0.466999
 0.452146  0.56766   0.0241094
 0.258463  0.922402  0.454959

In [38]:
x[:, 1] # it means to select the first column

3-element Vector{Float64}:
 0.6094543130917499
 0.4521462975867582
 0.25846320936481293

### Ranges
Ranges are useful shorthand notations that define a "vector" (one dimensional array) with equi-spaced entries. They are created with the following syntax:
```julia
start:stop # mainly for integers
start:step:stop
range(start, stop, length)
range(start, stop; step = ...)
```

In [39]:
r = 0:0.01:5

0.0:0.01:5.0

Ranges always include the first element and step until they _do not exceed_ the ending element. If possible, they include the stop element (as above).

In [40]:
r[end-3] # use `end` as index for the final element

4.97

Ranges are not unique to numeric data, and can be used with anything that extends their interface, e.g.

In [41]:
letterrange = 'a':'z'

'a':1:'z'

As ranges are printed in this short form, to see all their elements you can use `collect`, to transform the range into a `Vector`.

In [42]:
collect(letterrange)

26-element Vector{Char}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)
 'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)
 'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)
 'i': ASCII/Unicode U+0069 (category Ll: Letter, lowercase)
 'j': ASCII/Unicode U+006A (category Ll: Letter, lowercase)
 ⋮
 'r': ASCII/Unicode U+0072 (category Ll: Letter, lowercase)
 's': ASCII/Unicode U+0073 (category Ll: Letter, lowercase)
 't': ASCII/Unicode U+0074 (category Ll: Letter, lowercase)
 'u': ASCII/Unicode U+0075 (category Ll: Letter, lowercase)
 'v': ASCII/Unicode U+0076 (category Ll: Letter, lowercase)
 'w': ASCII/Unicode U+0077 (category Ll: Letter, lowercase)
 'x': ASCII/

Ranges are cool because they **do not store all elements in memory** like `Vector`s. Instead they produce the elements on the fly when necessary, and therefore are in general preferred over `Vector`s if the data is equi-spaced. 

Lastly, ranges are typically used to index into arrays. One can type `A[1:3]` to get the first 3 elements of `A`, or `A[end-2:end]` to get the last three elements of `A`. If `A` is multidimensional, the same type of indexing can be done for any dimension:

In [43]:
A = rand(4, 4)

4×4 Matrix{Float64}:
 0.968418   0.761232  0.0371632  0.616127
 0.3756     0.964616  0.912104   0.675814
 0.0755688  0.222625  0.483436   0.726692
 0.196823   0.419742  0.0334566  0.998256

In [44]:
A[1:3, 1]

3-element Vector{Float64}:
 0.9684184016131263
 0.37560027545677355
 0.07556877771009307

In [45]:
A[1:3, 1:3]

3×3 Matrix{Float64}:
 0.968418   0.761232  0.0371632
 0.3756     0.964616  0.912104
 0.0755688  0.222625  0.483436

## Iteration
Iteration in Julia is high-level. This means that not only it has an intuitive and simple syntax, but also iteration works with anything that can be iterated. Iteration can also be extended (more on that later).


### `for` loops

A `for` loop iterates over a container and executes a piece of code, until the iteration has gone through all the elements of the container. The syntax for a `for` loop is

```julia
for *var(s)* in *loop iterable*
    *loop body*
end
```

*you will notice that all Julia code-blocks end with `end`*

In [46]:
for n in 1:5
    println(n)
end

1
2
3
4
5


The nature of the iterating variable depends on what the iterating container has. For example, when iterating over a dictionary one iterates over pairs of key-value.

In [47]:
for pair in myphonebook # pair in myphonebook
    println(pair)
end

"Jenny" => "867-5309"
"Buzz Lightyear" => "∞ and beyond"
"Ghostbusters" => "555-2368"


Most of the time in such a scenario however, the variables that compose the iterable are decomposed directly after the `for` keyword, which also makes the code cleaner. For example:

In [48]:
for (key, val) in myphonebook # pair in myphonebook
    println("The number of $key is $val")
end

The number of Jenny is 867-5309
The number of Buzz Lightyear is ∞ and beyond
The number of Ghostbusters is 555-2368


In the context of `for`  loops, the `enumerate` iterator is often useful. It takes in an iterable and returns pairs of the index and the iterable value. 

In [49]:
for (i, v) in enumerate(rand(3))
    println("value of index $(i): $(v)")
end

value of index 1: 0.5820265200633368
value of index 2: 0.8815573487019367
value of index 3: 0.9633430025009551


### A note on command termination

Julia has a modern syntax parser that automatically understands when a command starts and ends. It does not require identation (like Python) or the `;` character (like C) to establish the end of a command. The following two are totally valid and syntactically identical Julia codes

In [50]:
        for (key,
val) in
                myphonebook
  println(
"The number of $key is $val"
        ) end

The number of Jenny is 867-5309
The number of Buzz Lightyear is ∞ and beyond
The number of Ghostbusters is 555-2368


In [51]:
for (key, val) in myphonebook println("The number of $key is $val") end

The number of Jenny is 867-5309
The number of Buzz Lightyear is ∞ and beyond
The number of Ghostbusters is 555-2368


However, code readability is important so it is strongly recommended to properly ident your code even if it is not enforced by the language!

### `while` loops

A `while` loop executes a code block until a boolean condition check (that happens at the start of the block) becomes `false`. Then the loop terminates (without executing the block again). The syntax for a standard `while` loop is

```julia
while *condition*
    *loop body*
end
```

In [52]:
n = 0
while n < 5
    n += 1
    println(n)
end

1
2
3
4
5



## Conditionals

Conditionals execute a specific code block depending on what is the outcome of a given boolean check. 
The  `&, |` are the boolean `and, or` operators.

### `if` block

In Julia, the syntax

```julia
if *condition 1*
    *option 1*
elseif *condition 2*
    *option 2*
else
    *option 3*
end
```

evaluates the conditions sequentially and executes the code-block of the first true condition.

In [53]:
x, y = 5, 6
if x > y
    x
else
    y
end

6

### Ternary operator

The ternary operator (named for having three arguments) is a convenience syntax for small `if` blocks with only two clauses. 

Specifically, the syntax

```julia
condition ? if_true : if_false
```

is syntactically equivalent to

```julia
if condition
    if_true
else
    if_false
end
```

For example

In [54]:
5 == 5.0 ? "yes" : "no"

"yes"

### `break` and `continue`
The keywords `continue` and `break` are often used with conditionals to skip an iteration or completely stop the iteration code block.

In [55]:
N = 1:100
for n in N
    isodd(n) && continue
    println(n)
    n > 10 && break
end

2
4
6
8
10
12


### List comprehension
The list comprehension syntax 
```julia
[expression(a) for a in collection if condition(a)]
```
is available as a convenience way to make a `Vector`. The `if` part is optional.

In [56]:
[    a^2 for a in 1:10 if iseven(a)      ]

5-element Vector{Int64}:
   4
  16
  36
  64
 100

## Functions
Functions are the bread and butter of Julia, which heavily supports functional programming.


### Function declaration

Functions are declared with two ways. First, the verbose

In [57]:
function f(x)
    # function body
    return x^2 # While `return` is not necessary, it is recommended for clarity
end

f (generic function with 1 method)

Or, you can define functions with the short form (best used for functions that only take up a single line of code)

In [58]:
f(x) = x^2  # equivalent with above

f (generic function with 1 method)

Functions are called using their name and parenthesis `()` enclosing the calling arguments:

In [58]:
f(5)

25

Functions in Julia support optional positional arguments, as well as keyword arguments. The **positional** arguments are **always given by their order**, while **keyword** arguments are **always given by their keyword**. Keyword arguments are all the arguments defined in a function after the symbol `;`. Example:

In [59]:
function g(x, y = 5; z = 2, w = 1)
    return x*z*y*w
end

g (generic function with 2 methods)

In [60]:
g(5) # give x. default y, z

50

In [61]:
g(5, 3) # give x, y. default z

30

In [62]:
g(5; z = 3) # give x, z. default y

75

In [63]:
g(2, 4; w = 0.1, z = 1.5) # give everything

1.2000000000000002

In [64]:
g(2, 4, 2) # keyword arguments can't be specified by position

MethodError: MethodError: no method matching g(::Int64, ::Int64, ::Int64)

Closest candidates are:
  g(::Any, ::Any; z, w)
   @ Main c:\Users\datse\OneDrive - University of Exeter\Teaching\Zero2Hero-JuliaWorkshop\1-JuliaIntro.ipynb:1
  g(::Any)
   @ Main c:\Users\datse\OneDrive - University of Exeter\Teaching\Zero2Hero-JuliaWorkshop\1-JuliaIntro.ipynb:1


###  Passing by reference: mutating vs. non-mutating functions

You can divide Julia variables into two categories: **mutable** and **immutable**. Mutable means that the values of your data can be changed in-place, i.e. literally in the place in memory the variable is stored in the computer. Immutable data cannot be changed after creation, and thus the only way to change part of immutable data is to actually make a brand new immutable object from scratch. Use `isimmutable(v)` to check if value `v` is immutable or not.

For example, `Vector`s are mutable in Julia:

In [65]:
x = [5, 5, 5]
x[1] = 6 # change first entry of x
x

3-element Vector{Int64}:
 6
 5
 5

But e.g. `Tuple`s are immutable:

In [66]:
x = (5, 5, 5)
x[1] = 6

MethodError: MethodError: no method matching setindex!(::Tuple{Int64, Int64, Int64}, ::Int64, ::Int64)

In [67]:
x = (6, 5, 5)

(6, 5, 5)

Julia **passes values by reference**. This means that if a mutable object is given to a function, and this object is mutated inside the function, the final result is kept at the passed object. E.g.:

In [68]:
function add3!(x)
    x[1] += 3
    return x
end

x = [5, 5, 5]
add3!(x)
x

3-element Vector{Int64}:
 8
 5
 5

**By convention**, functions with name ending in `!` alter their (mutable) arguments and functions lacking `!` do not. Typically the first argument of a function that ends in `!` is mutated.

For example, let's look at the difference between `sort` and `sort!`.

In [69]:
v = [3, 5, 2]

3-element Vector{Int64}:
 3
 5
 2

In [70]:
sort(v)

3-element Vector{Int64}:
 2
 3
 5

In [71]:
v

3-element Vector{Int64}:
 3
 5
 2

`sort(v)` returns a sorted array that contains the same elements as `v`, but `v` is left unchanged. <br><br>

On the other hand, when we run `sort!(v)`, the contents of v are sorted within the array `v`.

In [72]:
sort!(v)

3-element Vector{Int64}:
 2
 3
 5

In [73]:
v

3-element Vector{Int64}:
 2
 3
 5

### Functions as arguments

Functions, like literally anything else in Julia, are objects that can be passed around like any other value. Including giving them as arguments to other functions. 

A typical application of this is with the `findall` and related functions, that find the indices of all elements in a collection that return `true` for a particular expression.

In [14]:
expression(x) = (x < 0.5) | (x > 1.5)
x = 0:0.1:2
valid_indices = findall(expression, x)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
 17
 18
 19
 20
 21

### The help system

Typing `?` followed by a function (or type) name will display its documentation string. Alternatively you can type `@doc` and then the function name.

For example

In [75]:
? cos

ErrorException: syntax: invalid identifier name "?"

## Broadcasting

_This subsection can be skipped for the sake of time_


Broadcasting is a convenient syntax for applying any function over the elements of an iterable input. I.e., the result is a new iterable whose elements is the function application of the elements of the input.

Broadcasting is done via the simple syntax of adding a dot `.` before the parenthesis in the function call: `g.(x)`.

In [76]:
h(x, y = 1) = x + y

h (generic function with 2 methods)

In [77]:
x = [1, 2, 3]
h.(x) # without 2nd argument, `h` is just `x + 1`

3-element Vector{Int64}:
 2
 3
 4

In [78]:
y = [1, 2, 3]
h.(x, y) # each element of `x` is added to the corresponding element of `y`

3-element Vector{Int64}:
 2
 4
 6

Let's now apply it to a vector `x`

In [79]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [80]:
h.(x)

3-element Vector{Int64}:
 2
 3
 4

Broadcasting can be useful when the number of operations is small and one can easily reason about the way the operations would be broadcasted across input(s). 

A typical example of broadcasting is to make an exponential range, which doesn't have a pre-made function in Julia:

In [81]:
exp_range = 10.0 .^ (-3:3)

7-element Vector{Float64}:
    0.001
    0.010000000000000002
    0.1
    1.0
   10.0
  100.0
 1000.0

*(notice that for infix operators (like `+, -`) the `.` is put before the operator)*

# Exercises - basics

**Important note for all exercises: when an exercise says _"use function `function_name` to do something"_, you need to first learn how to use the function. For this, you access the function's documentation string, using the help mode (type `?` or `@doc` in the Julia console and then type the function name)!**


## Babylonian square root
To get the square root of $y$ Babylonians used the algorithm $x_{n+1} = \frac{1}{2}(x_n + \frac{y}{x_n})$ iteratively starting from some value $x_0$ to converge to $x_n \to \sqrt{y}$ as $n\to \infty$. Implement this algorithm in a function `babylonian(y, ε, x0 = 1)` (default optional argument `x0`), that takes some convergence tolerance `ε` to compare with the built-in `sqrt(y)`. The function should return the steps it took to reach the square root value within given tolerance.

_Hint: for this exercise you only need a `while` code block without any other code structures such as `for, if, ...`._

In [1]:
function babylonian(y, ϵ, x0=1)
    x = x0
    while (abs(x-sqrt(y))>ϵ)
        x = (x+y/x)/2
    end
    x
end 

babylonian (generic function with 2 methods)

In [2]:
babylonian(4, 0.000005)

2.0000000929222947


## Counting nucleotides
Create a function that given a DNA strand (as a `String`, e.g. `"AGAGAGATCCCTTA"`) it counts how much of each nucleotide (A G T or C) is present in the strand and returns the result as a dictionary mapping the nucleotides to their counts. The function should throw an error (using the `error` function) if an invalid nucleotide is encountered. Test your result with `"ATATATAGGCCAX"` and `"ATATATAGGCCAA"`.

*Hint: Strings are iterables! They iterate over the characters they contain.*

In [3]:
function nucleotide_count(s)
    count = Dict('A'=>0, 'G'=>0, 'T'=>0, 'C'=>0)
    flag = false
    
    for c in s
        for (k, v) in count
            if(k==c) 
                count[k] = v+1
                flag = true
                break
            end
        end
        if(!flag)
            err1or("Invalid Sequence")
        end
    end
    count
end

nucleotide_count (generic function with 1 method)

In [2]:
nucleotide_count("ATATATAGGCCAA")

Dict{Char, Int64} with 4 entries:
  'A' => 6
  'G' => 2
  'T' => 3
  'C' => 2

## Fibonacci numbers
Using recursion (a function that calls itself) create a function that given an integer `n` it returns the `n`-th [Fibonacci number](https://en.wikipedia.org/wiki/Fibonacci_number). Apply it using `map` to the range `1:8` to get the result `[1,1,2,3,5,8,13]`.

In [4]:
function f(n)
    (n==1 || n==2) ? 1 : f(n-1) + f(n-2)
end

f (generic function with 1 method)

In [5]:
x = [map(f, collect(1:8))]

1-element Vector{Vector{Int64}}:
 [1, 1, 2, 3, 5, 8, 13, 21]

## Robot movement

Simulate the movement of a robot in a two-dimensional integer grid. The robot can perform three actions: turn left, right, or move for 1 step in the direction it is facing. The robot receives instructions in the form of strings composed entirely by the letters `L, R, M` (meaning "turn left", "turn right" and "move 1 step forwards"). Write a function `move_robot(u0, instructions)` which receives as input:

1. The robot's starting position `u0`, a tuple of `(x::Int, y::Int, d::Char)`, where `x, y` encode the starting position, and `d` the orientation, which can be a character of `'N', 'S', 'E', 'W'`.
2. The instructions which is a string sequencing the individual instructions, e.g., `"LLMMMRMMRM"`.

The function should return `uf` which the robot's final position, which is a tuple of same type as `u0`.

Test your function with the inputs `u0 = (7, 3, 'N')` and `instructions = "RMMLML"`, which should output `uf = (9, 4, 'W')`.

_Hint: one way to solve this exercise is with lots and lots of `if` statements. Another is to create 2-tuples of movement vectors for each possible orientation. For rotation commands, the orientation vector gets updated. For movement commands, the oriantation vector is added to current position_

In [6]:
function move_robot(u0, instructions)
    x = u0[1]
    y = u0[2]
    d = u0[3]
    
    directions = ('N', 'E', 'S', 'W')
    index = 0
    for (i, v) in enumerate(directions)
        if v == d
            index = i 
        end
    end

    for c in instructions
        if (c == 'L') 
            index == 1 ? index=4 : index-=1
            d = directions[index]
        elseif (c == 'R')
            index == 4 ? index=1 : index+=1
            d = directions[index]
        elseif (c == 'M')
            movement = ([x , y+1, 'N'], [x+1, y, 'E'], [x, y-1, 'S'], [x-1, y, 'W'])
            x = movement[index][1]
            y = movement[index][2]
        end
    end
    uf = (x, y, d)
end

move_robot (generic function with 1 method)

In [7]:
move_robot((7, 3, 'N'), "RMMLML")

(9, 4, 'W')


## Hamming distance

Create a function that calculates the Hamming distance of two equal DNA strands, given as strings. This distance is defined by counting (sequentially) the number of non-equal letters in the two strands, e.g. `"ATA"` and `"ATC"` have distance of 1, while `"ATC"` and `"CAT"` have distance of 3. 

*Hint: this exercise has a one-liner solution, using the `zip` and `count` functions.*

In [8]:
distance(s1, s2) = count((c)->c[1]!=c[2], collect(zip(s1, s2)))

distance (generic function with 1 method)

In [9]:
distance("ATA", "ATC")

1

In [10]:
distance("ATC", "CAT")

3

---

# Basic plotting with Makie

This block serves as a tini-tiny introduction to plotting in Julia using [Makie](https://docs.makie.org/stable/), which has to be the best plotting framework out there _in any programming language_ (personal opinion).

Makie offers several plotting backends, but for the purpose of this tutorial we will use its Cairo backend, focused on 2D publication quality graphics.

Makie is an "external package"; it is not installed with Julia. New Julia packages are installed using Julia's package manager. This itself is a package for the Julia language, so we need to learn how to use it first!

## Environments and installing packages

One way one "imports" a package into scope is with `import`:

In [3]:
import Pkg # the package manager of Julia is a package itself

This is the same as Python's `import`: it brings a package into scope, but none of its functions are accessible from the top level. They need to be prefaced with the package name and dot `.`. For example:

In [4]:
Pkg.add

add (generic function with 7 methods)

Before installing any packages, we will first activate a dedicated _environment_: a "space" Julia will add packages to. This environment will simply be the directory that contains this Jupyter notebook:

In [5]:
Pkg.activate(@__DIR__) # `@__DIR__` always gives the directory of where it was run

  Activating project at `~/Repository/Zero2Hero-JuliaWorkshop`


We can examine the packages in the environment by running `Pkg.status`

In [6]:
Pkg.status()

Status `~/Repository/Zero2Hero-JuliaWorkshop/Project.toml`
 ⌃ [6e4b80f9] BenchmarkTools v1.3.2
→  [a134a8b2] BlackBoxOptim v0.6.2
→⌃ [13f3f980] CairoMakie v0.11.1
   [a93c6f00] DataFrames v1.6.1
→⌃ [31c24e10] Distributions v0.25.103
→  [634d3b9d] DrWatson v2.13.0
   [fa6b7ba4] DualNumbers v0.6.8
→  [61744808] DynamicalSystems v3.2.3
→  [0987c9cc] MonteCarloMeasurements v1.1.6
→⌃ [1dea7af3] OrdinaryDiffEq v6.59.2
→  [1a8c2f83] Query v1.0.0
   [1e83bf80] StaticArraysCore v1.4.2
 ⌃ [0c5d862f] Symbolics v5.10.0
→  [1986cc42] Unitful v1.19.0
Info Packages marked with → are not downloaded, use `instantiate` to download
Info Packages marked with ⌃ have new versions available and may be upgradable.


Now, if you have setup this notebook as instructed, by cloning the entire Julia Zero2Hero repository and following the installation instructions, then there is already a list of packages. These are the packages (and their versions) that are used in the Julia Zero2Hero tutorial. If you have only downloaded the Jupyter notebook by itself, the above environment will be empty! 

To add a new package to the environment we use the `add` function.
The simplest way to install new packages is by its name. 
Julia has an extensive list of cutting edge packages that you can explore in a categorized format in [juliapackages.com](https://juliapackages.com/)! Once you have the name, you can simply call `Pkg.add("Name")`.

In [7]:
Pkg.add("CairoMakie")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed NonlinearSolve ───────────── v2.8.2
   Installed QueryOperators ───────────── v0.9.3
   Installed PredefinedDynamicalSystems ─ v1.2.0
   Installed DSP ──────────────────────── v0.7.9
   Installed Unitful ──────────────────── v1.19.0
   Installed Permutations ─────────────── v0.4.18
   Installed StableHashTraits ─────────── v1.1.1
   Installed PDMats ───────────────────── v0.11.30
   Installed Accessors ────────────────── v0.1.33
   Installed MarchingCubes ────────────── v0.1.8
   Installed ConcurrentUtilities ──────── v2.3.0
   Installed Polyester ────────────────── v0.7.9
   Installed TriangularSolve ──────────── v0.1.20
   Installed Roots ────────────────────── v2.0.22
   Installed TimeseriesSurrogates ─────── v2.6.3
   Installed DelayEmbeddings ──────────── v2.7.4
   Installed CPUTime ──────────────────── v1.0.0
   Installed FilePaths ────────────────── v0.8.3
   Installed SIMD 

  ✓ Measurements → MeasurementsRecipesBaseExt
  ✓ StableHashTraits
  ✓ SIMD
  ✓ FilePaths
  ✓ Gettext_jll
  ✓ XSLT_jll
  ✓ LightXML
  ✓ SortingAlgorithms
  ✓ QuadGK
  ✓ SimplePartitions
  ✓ MultivariatePolynomials
  ✓ OpenSSL
  ✓ Setfield
  ✓ Neighborhood
  ✓ Accessors
  ✓ GPUArraysCore
  ✓ OffsetArrays
  ✓ SpecialFunctions
  ✓ EnzymeCore
  ✓ ArrayInterface
  ✓ Graphs
  ✓ Xorg_libxcb_jll
  ✓ QueryOperators
  ✓ IterableTables
  ✓ Polynomials
  ✓ ExactPredicates
  ✓ Glib_jll
  ✓ StatsBase
  ✓ JLD2
  ✓ DynamicPolynomials
  ✓ StateSpaceSets
  ✓ Accessors → AccessorsIntervalSetsExt
  ✓ Roots
  ✓ StructArrays
  ✓ Accessors → AccessorsStaticArraysExt
  ✓ StackViews
  ✓ PaddedViews
  ✓ HTTP
  ✓ Sparspak
  ✓ DiffRules
  ✓ DualNumbers
  ✓ SpecialFunctions → SpecialFunctionsChainRulesCoreExt
  ✓ Interpolations
  ✓ Measurements → MeasurementsSpecialFunctionsExt
  ✓ LombScargle
  ✓ ArrayInterface → ArrayInterfaceStaticArraysCoreExt
  ✓ Unitful
  ✓ ArrayInterface → ArrayInterfaceGPUArraysCoreExt
  ✓

Now, if you setup this tutorial material as instructed, the command above will not have done anything because you have already run the file `install_and_compile.jl` which would have installed for you all the packages in the Zero2Hero environment!
Otherwise, this command will have installed CairoMakie for you!

To use a package, you would typically prefer `using PackageName` over `import`. `using` brings into scope all functions that the package _chooses_ to publicly export. The reason that in Julia you almost always use `using` instead of `import` (unlike e.g., in Python) will become clear in the second block on multiple dispatch. 

For now, let's simply do:

In [ ]:
using CairoMakie

This brings functions from this package into your current working scope. For example

In [ ]:
lines # this function didn't exist before `using CairoMakie`

## Initializing plots

_before going through the plotting tutorial we'll quickly change the default figure and size for easier visualization in a zoomed-in Jupyter notebook; themeing will not actually be discussed in this brief introduction_

In [ ]:
update_theme!(size = (500, 300), fontsize = 16)

Alright, the most straight-forward usage of Makie is to directly call one of the plotting functions, like `lines, scatter, barplot, ...` giving in the x and y coordinates of data to be plotted.

In [ ]:
x = 1:5
y = [1, 3, 2, 4, 5]
fig, ax, plot_object = lines(x, y)

These plotting functions return three values. `fig` is a `Figure` object, which is the overarching figure that everything else is contained in. `ax` is an `Axis` object, which is a window with coordinates, labels, tickmarks, etc., in which data are visualized. The third output is the specific plot object (here a `Lines` object) for which we do not care about at the moment.

In any case, this all means that when we called `lines(...)` the function did a lot of things: it initialized a figure, it initialized an axis in that figure, and then line-plotted some data. This also means that `lines` and similar functions never update existing plots (which is contrary to the default behavior of e.g. the Python library `matplotlib`):

In [ ]:
z = reverse(y)
scatter(x, z; color = "tomato") # makes a new plot!

To update an existing plot, you need to call the **in-place**, or **mutating**, version of the plotting functions, i.e., the version ending in `!`, giving it the axis to plot in (if not given, the last-used axis is used)

In [ ]:
fig, ax, plot_object = lines(x, y)
scatter!(ax, x, z; color = "tomato")

Ops!? what happened here? Why is there no plot? It's because the return value of `scatter!` isn't a figure, but rather just the plot object, since `scatter!` doesn't initialize a figure. We need to explicitly return the figure as the return value of the code block for it to be displayed:

In [ ]:
fig

We won't really get into too much detail of the options each plotting function has; they are several dozens, line width, marker style, size, color, fill, and many, many others. They are provided as **keyword arguments** to the plotting functions, e.g., `lines(x, y; color = "purple", linewidth = 2)`. Best to check the online documentation of Makie, or the docstring of the functions, for details on all these options.

What is important to know however, is that all of these options can be vectors, just like the input data. E.g., if you'd like each marker to have a different size, you'd just pass the vector of sizes as the `markersize` attribute (and similarly with color, width, and everything else).

In [ ]:
scatter(x, z;
    markersize = 10y, color = y, colormap = "thermal",
    marker = ['a', '♠', '⊚', :rect, :circle]
)

## Layouting axes in figures

One of the strongest features of Makie is its layouting system, that allows you to create sub-panels of figures with as much ease as it is saying where an axis should be in normal English.

To add an axis to a figure, you simply initialize the axis at the expected location using the intuitive **matrix indexing syntax**: `fig[row, col]`. I.e., you imagine the figure to be a "matrix of axes" and add an axis at the given row and column.

In [ ]:
fig = Figure() # initialize a figure with default settings
# create an Axis into `fig[1,1]`, and keep track of it in a variable!
ax1 = Axis(fig[1,1])
# i.e., give the location of the axis directly in the `Axis` constructor!
fig # don't forget to return the figure for it to be plotted!

we now add another axis in the second "column"

In [ ]:
ax2 = Axis(fig[1,2])
fig

Makie's automatic layouting capabilities make everything fit and be the correct size given the figure size constrain!

Furthermore, they understand the dimensional extent of the "matrix of axis" even without it being yet full of axes:

In [ ]:
ax4 = fig[1,4] = Axis(fig;
    # This is the way to adjust axis properties during creation:
    title = "wow!",
    xlabel = "much axis",
    ylabel = "why left empty?"
)
fig

In [ ]:
# and this way you adjust axis properties after creation:
ax1.xticks = ([1,2,9], ["1", "4", "8"]) # ticks and their labels
ax1.xlabel = "bamboozled!"
fig

Not only that, but just like normal matrices, one could utilize the syntax `fig[col, row]` using _ranges_, such as `1:2`. For example, we could specify an axis to span a range of 2, or 3 "positions" in the "grid of axes" that the figure represents:

In [ ]:
x = range(0, 4π; length = 100)
y = sin.(x)

fig = Figure(size = (600, 400))

# notice that we can call plotting functions directly on figure indices
# if we do not care about storing the created axes for later use!
# (we therefore use the non-`!` version, so that an axes is created)
lines(fig[1, 1], x, y, color = Cycled(1))
lines(fig[1, 2:3], x, y, color = Cycled(2))

fig

In [ ]:
lines(fig[2, 1:3], x, y, color = Cycled(3))
fig

In [ ]:
lines(fig[:, 4], x, y, color = Cycled(4))
fig

## Legends and colorbars

The `Axis` structure we have encountered above is a `Block` in the context of Makie. Two more `Block`s that are typically useful in scientific visualizations are the `Legend` and the `Colorbar`. Just like an `Axis` they could be placed arbitrarily and anywhere in a figure, even on top of existing axes.

### Legend

Legend has a simple automated way of being created.
You can assign a label to each plotted element of an axes by providing a value to the keyword `label`.

In [ ]:
x = range(0, 10; length = 20)
lines(x, sin; label = "sin")  # makes a figure
scatter!(x, cos; label = "cos", color = "purple") # uses last-used figure
current_figure() # return (and hence display) last-used figure

To add an axis that automatically displays the labels we created, we use `axislegend`

In [ ]:
axislegend() # first argument is the axis to use. Defaults to last-used axis.
current_figure()

Of course, sometimes the manual creation and placement of a legend is necessary. In such a case, one collects the plotted objects that we haven't cared about so far, and gives them to a `Legend` object:

In [ ]:
fig = Figure()
x = range(0, 10; length = 20)
ax1, li1 = lines(fig[1, 1], x, sin)
ax2, sc2 = scatter(fig[2, 1], x, cos; color = "purple")
Legend(fig[1:2, 2], [li1, sc2], ["ημίτονο", "cosinus"])
fig

## Learning more about Makie

Makie is the best the strongest the most amazing plotting framework (personal opinion). In this tini-tiny block we've only looked at a small subset of Makie's functionality. We haven't even touched the strongest feature of Makie, which is interactive visualizations and animations! In any case, you can learn more about Makie in the online documentation. For example:

- You can read about the different available plotting functions with visual examples visit the [Plotting Functions](https://docs.makie.org/stable/examples/plotting_functions/index.html#plotting_functions) section.

- If you want to learn more about making complex figures with nested sublayouts, have a look at the [Layout Tutorial](https://docs.makie.org/stable/tutorials/layout-tutorial/index.html#layout_tutorial) section.

- If you're interested in creating interactive visualizations that use Makie's special `Observables` workflow, this is explained in more detail in the [Observables & Interaction](https://docs.makie.org/stable/documentation/nodes/index.html#observables_interaction) section.

- Lastly, see the [Animations](https://docs.makie.org/stable/documentation/animation/index.html#animations) section for making animated movies.

# Exercises - plotting

## Taylor expansion of sine

Plot the sine function and its progressive Taylor expansion series:

$$
\sin(x) \approx x - x^3/6 + x^5/120
$$

First, plot $\sin(x)$, then the progressively added Taylor terms: $x$, $x - x^3/6$, $x - x^3/6 + x^5/120$. For each plotted curve add a legend entry and in the end display the legend as well.



## Semi-transparent histograms

Use the following code to initialize some histogram data.

In [ ]:
using Random: Xoshiro
rng = Xoshiro(1234)
xp1 = 0.2randn(rng, 10_000) .+ 0.5
p2 = 0.5randn(rng, 10_000)
edges = -2:0.1:2;

Using Makie's `hist` function, make the following plot:


![makie_ex_fig_1.png](makie_ex_fig_1.png)


_hint: to make transparent colors in Makie you provide a 2-tuple of the color and the alpha transparency value as the `color` keyword, such as `color = ("red", 0.75)`._

## Cool spiral


Pick 6 colors that you like and make the following figure:

![makie_ex_fig_2.png](makie_ex_fig_2.png)


_hint 1: The colored rectangles are just colored `Box` `Block`s. Instead of initializing an axis, you create a `Box` object, with the same syntax, at the location of interest. E.g., the first box is done with the code:_

```julia
Box(fig[1, 1:2]; color = "something", strokewidth = 0)
```

_hint 2: You can make axes on top of other elements. To make the line plot on top of the boxes, you first initialize the line data using_
```julia
n = 4
t = 0:0.01:2n*π
x = (2n*π .- t) .* cos.(t)
y = (2n*π .- t) .* sin.(t)
```
_and then make an axis over the whole figure `Axis(fig[:, :])` to plot in. To remove the spines of the axis use the functions `hidedecorations!` and `hidespines!`_.


# Basic performance considerations

## Type stability

Julia matches the performance of C/Fortran not because of better hardware or better compilers than e.g., Python uses, but because of design. Julia is interactive like Python, but it is not an interpreted language, it is a **compiled** one. This means that **every function call in Julia first gets compiled, based on the exact input types**. Then it is executed.

*(this compilation only happens once for each unique combination of input types)*

When the compiler compiles a function, these types of every variable can be tracked throughout the function and all datastructures are mapped uniquely and deterministically all the way from input to output. This allows the compiler to make all the optimizations that e.g. the compilation of a C language code would do. And this (in a nutshell) is what results in the same performance as C/Fortran.

This tracking of types mentioned above only works if **the type of every variable remains the same type throughout the function's operations**. Notice the distinction: the _type_ (i.e. all floating point variables remain floats) is constant, but of course the _value_ could change (i.e. going from `515134.515` to `123415.242` is fine).

What if this doesn't happen? Then we have the case of **Type instability**, which is what makes beginner's code slow in 99% of the cases. 

Let's look at the following illustrative scenario:

In [ ]:
Pkg.activate(@__DIR__)
using BenchmarkTools

In [ ]:
@noinline function mymax(init, x)
    s = init
    for xi in x
        s = s < xi ? xi : s
    end
    return s
end

# benchmark it
using BenchmarkTools: @btime
r = rand(Int, 1000);
@btime mymax(-Inf32, $r);

In [ ]:
@btime mymax(-Inf, $r);

In [ ]:
@btime mymax(typemin(Int), $r);

`mymax` is a **type-unstable function**, which means it has suboptimal performance. 

you can see this by using the `@code_warntype` macro

In [ ]:
@code_warntype mymax(-Inf, r)

If you don't understand this text, no worries: what you care is that red text means bad type instability, and yellow means type instability that may or may not matter for performance. Whenever a `for` loop is involved there will one yellow line per `for` loop with a `Union` type including `Nothing`. You can ignore this and focus on all other yellow or red colors.

This type instability problem is rather mild here due to the trivial contrived example. It becomes much, much worse if the instability happens in more than one variable, if the instability happens with more than 2 types, or if the types involved in the instability are much more complicated. 

For example, it can become particularly bad once the type instability involves functions.

In [ ]:
function add_funs(x, F)
    F[1](x) + F[2](x)
end

F1 = [sin, cos]
F2 = (sin, cos)

@btime add_funs(1.0, $F1)
@btime add_funs(1.0, $F2);

In [ ]:
@code_warntype add_funs(1.0, F1)

This happens because functions are their own types:

In [ ]:
typeof(cos)

and wrapping them in a vector creates a vector of their super type:

In [ ]:
typeof([sin, cos])

while the tuple retains the individual types

In [ ]:
typeof((sin, cos))

### Scopes

In general Julia has two scopes: global scope (the one we use here, in this notebook) and local scope. Local scope is introduced by most code blocks, e.g. functions, `for` or `while` loops but *not* from conditional code blocks (`if`). The details of the scopes are mostly relevant for package development and can be found in the [Julia manual](https://docs.julialang.org/en/latest/manual/variables-and-scoping/). 

What is important for us is that by definition, **everything in global scope is type-unstable** and thus not performant. This happens because Julia is not a statically typed language, but a dynamically typed one. Therefore one can do

In [ ]:
x = 5
x = "string"

which is not possible in e.g. C.

The performance that global scope has in code is truly massive. Here are some global evaluations of some code

In [ ]:
x, y = rand(1000), rand(1000)
a = 0.0
@btime for i in 1:length(x)
    global a += x[i]^2 + y[i]^2
end

and here are essentially the same operations but done within a function:

In [ ]:
function localf(x, y)
    a = zero(eltype(x))
    for i in 1:length(x)
        a += x[i]^2 + y[i]^2
    end
    return a
end

@btime localf(x, y);

This is more than a 170x slowdown!!!

### Conclusions so far

1. **Put all performance critical parts of your code inside a function** to avoid global scope
2. **Ensure that your functions are type-stable**, meaning that the types of the variables inside the function do not change. The macro `@code_warntype` can help with that!

## Allocation of mutable containers

Another thing that is important for performance is allocation. What must be understood is that when one writes

In [ ]:
x = rand(2, 2)

or 

In [ ]:
y = x[1, :]

this *allocates* some part of your memory to store this **mutable** container that `x` or `y` represents. Creating mutable things always allocates memory. In general when you are creating something mutable you always pay two costs:

1. the cost to actually calculate the numbers that go into this thing (here e.g. the cost of calling `rand()`)
2. the cost to allocate some memory to store 1000 numbers of type `Float64`.

In general you should try to avoid allocations, by more clever design of your algorithms and pre-allocating as much as possible, as is instructed by this section of [Julia's performance tips](https://docs.julialang.org/en/latest/manual/performance-tips/#Pre-allocating-outputs-1).

### Example: using `mul!` and `view` to make a non-allocating function

Let's have a look at the following function

In [ ]:
function sum_matrix_vector(A, B)
    out = A*B[:, 1]
    for j in 2:size(B, 2)
        out += A*B[:, j]
    end
    return out
end

n = 50
A = rand(n,n)
B = rand(n,n)
out1 = sum_matrix_vector(A,B)
summary(out1)

And let's benchmark its performance

In [ ]:
using BenchmarkTools
@btime sum_matrix_vector($A, $B);

Now we'll make a second version of this function. One that uses in-place multiplication of matrix-vector into a pre-allocated container. And one that uses `view` to view into the matrix `B` without making a copy every time.

In [ ]:
function sum_matrix_vector_nonalloc(A, B)
    # set up
    out = zeros(eltype(B), size(B, 2))
    dummy = copy(out)
    return sum_matrix_vector!(out, dummy, A, B)
end

using LinearAlgebra: mul!
function sum_matrix_vector!(out, dummy, A, B)
    # all computations are in-place
    fill!(out, 0)
    for j in 1:size(B, 2)
        mul!(dummy, A, view(B, :, j))
        out .+= dummy # notice the `.`
    end
    return out
end

In [ ]:
sum_matrix_vector(A, B) == sum_matrix_vector_nonalloc(A, B)

In [ ]:
@btime sum_matrix_vector_nonalloc($A, $B);

As you can see, the improvement in performance is really major! Not only that, but the pre-allocated containers `out, dummy` only need to be made once; different `A, B` do not need re-initialization of `out, dummy` (you'd need to skip the setup part in this case).

## Performance tips summary

1. **Put all performance critical parts of your code inside a function** to avoid global scope
2. **Ensure that your functions are type-stable**, meaning that the types of the variables inside the function do not change. The macro `@code_warntype` can help with that!
3. **Create as little new large mutable entities in your function as possible**, to avoid memory allocations.
4. **Separate your functions into a set-up function and a computing function.** The first initializes all data structures you need, while the second does the actual algorithmic computations. The second function should be **non-allocating**.

# Exercises - performance

## Collatz conjecture
Given a positive integer, create a function that counts the steps it takes to reach `1` following the [Collatz conjecture algorithm](https://en.wikipedia.org/wiki/Collatz_conjecture) (if $n$ is odd do $n=3n+1$ otherwise do $n=n/2$ until you reach 1). Test it with the number 100 to get 25. Ensure that your function is type stable by calling `@code_warntype your_function(100)` and getting no red text.

*Hint: make a type-stable function by using `÷`, (`\div<TAB>`): In Julia `/` is the floating point devision operator and thus `n/m` is always a float number even if `n, m` are integers.*


## Henon map

Create a function that given `u0, N` it creates an orbit of length `N` of the Henon map

$$
\begin{aligned}
x_{n+1} &= 1 - 1.4x^2_n+y_n \\
y_{n+1} &= 0.3x_n
\end{aligned}
$$

This map produces an orbit iteratively, i.e. starting from `u0 = (x0, y0)` one  applies the above rule to get `u1 = (x1, y1)`, and then applies the rule again on `u1` to get `u2`, and so on. The orbit consists of the sequence of states `[u0, u1, u2, ...]`. Use `u0 = (0.0, 0.0)`.

_Hint: The most performant way to represent the states is via Tuples of two floats, not via `Vector`s. To solve, create two functions: one that initializes a length-`N` vector of dummy tuples using `fill`, and one that modifies this pre-initialized vector with the new tuples._
